package com.curbappealbd.curbappeal.domain;

import javax.persistence.*;
import java.util.Arrays;

/**
 * ImageModel class that is the object type to be stored in the database
 * @author Fizzor
 */
@Entity
@Table(name="image_model")
public class ImageModel {

	//all of the local variable of the class
	
	//the id is autogenerated to always be unique
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long id;

    @Column(name = "name")
    private String name;

    @Column(name = "type")
    private String type;

    @Column(name = "url")
    private String url;

    @Column(name = "position")
    private int position;

    /**
	 * Constructor with none of the variables being dictated
	 * @author Fizzor
	 * 
	 * @return ImageModel returns a new object of type ImageModel with the passed in settings
	 */
    public ImageModel(){}

    /**
	 * Constructor with only name, type and url being dictated
	 * @author Fizzor
	 * @param name String is the name of the image file
	 * @param type String is the file type
	 * @param url String is the url where the image is stored on cloudinary
	 * 
	 * @return ImageModel returns a new object of type ImageModel with the passed in settings
	 */
    public ImageModel(String name, String type, String url){
        this.name = name;
        this.type = type;
        this.url = url;
    }

    /**
	 * Constructor with all the variables accept id being dictated
	 * @author Fizzor
	 * @param position int is the position of the image in the gallery
	 * @param name String is the name of the image file
	 * @param type String is the file type
	 * @param url String is the url where the image is stored on cloudinary
	 * 
	 * @return ImageModel returns a new object of type ImageModel with the passed in settings
	 */
    public ImageModel(int position, String name, String type, String url){
        this.position = position;
        this.name = name;
        this.type = type;
        this.url = url;
    }

    //returns the value of id
    public Long getId(){

        return this.id;
    }

    //sets the value of id
    public void setId(Long id){

        this.id = id;
    }

    //returns the value of name
    public String getName(){

        return this.name;
    }

    //sets the value of name
    public void setName(String name){

        this.name = name;
    }

    //returns the value of type
    public String getType(){

        return this.type;
    }

    //sets the value of type
    public void setType(String type){

        this.type = type;
    }

    //returns the value of url
    public String getUrl(){

        return this.url;
    }

    //sets the value of url
    public void setUrl(String url){
        this.url = url;
    }

    //returns the value of position
    public int getPosition() {
        return position;
    }

    //sets the value of position
    public void setPosition(int position) {
        this.position = position;
    }

    //allows for boolean operations of the class with other objects of the same type
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ImageModel that = (ImageModel) o;

        return id != null ? id.equals(that.id) : that.id == null;
    }

    //returns the hashcode of the id
    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }

    //returns a stringified version of the class
    @Override
    public String toString() {
        return "ImageModel{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", type='" + type + '\'' +
                ", url=" + url +
                '}';
    }
}